services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api
    env_file:
      - .env
    environment:
      SERVER_PORT: 8080
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
